import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "scripts/data/법정동코드 전체자료.txt"
OUTPUT = (
    ROOT
    / "backend/src/main/resources/db/migration/V2__seed_regions.sql"
)


def sql_string(value):
    return "'" + value.replace("'", "''") + "'"


def main():
    # 원본은 CP949로 인코딩된 탭 구분 파일입니다.
    with SOURCE.open(encoding="cp949", newline="") as source_file:
        reader = csv.DictReader(source_file, delimiter="\t")
        required = {"법정동코드", "법정동명", "폐지여부"}
        if not required.issubset(reader.fieldnames or []):
            raise ValueError("원본 파일의 컬럼을 확인하세요.")

        rows = []
        for row in reader:
            if row["폐지여부"].strip() != "존재":
                continue

            code = row["법정동코드"].strip()
            name = row["법정동명"].strip()

            if len(code) != 10 or not code.isdigit():
                raise ValueError(f"잘못된 법정동코드: {code}")

            # 읍·면·동·리 행은 제외합니다.
            if code[5:] != "00000":
                continue

            # 시도 자체의 행은 제외합니다.
            if code[2:5] == "000":
                continue

            rows.append((code, name))

    names = {name for _, name in rows}
    regions = {}

    for code, name in rows:
        parts = name.split()

        if len(parts) == 1 and name == "세종특별자치시":
            # 세종은 별도의 시·군·구가 없어 같은 이름을 사용합니다.
            sido_name = name
            sigungu_name = name
        elif len(parts) == 2:
            sido_name, sigungu_name = parts
        elif len(parts) == 3:
            # "경기도 수원시 장안구"는 부모 수원시 행으로 대체합니다.
            parent_name = " ".join(parts[:2])
            if not parts[1].endswith("시") or parent_name not in names:
                raise ValueError(f"부모 시를 확인해야 합니다: {name}")
            continue
        else:
            raise ValueError(f"처리 규칙을 확인해야 합니다: {name}")

        region_code = code[:5]
        if region_code in regions:
            raise ValueError(f"중복 지역 코드: {region_code}")

        regions[region_code] = (sido_name, sigungu_name)

    # 이슈에서 명시한 주요 조건을 검증합니다.
    if regions.get("11200") != ("서울특별시", "성동구"):
        raise ValueError("성동구 데이터가 올바르지 않습니다.")
    if regions.get("41110") != ("경기도", "수원시"):
        raise ValueError("수원시 데이터가 올바르지 않습니다.")
    if "41111" in regions:
        raise ValueError("수원시 장안구가 별도 지역으로 남았습니다.")

    prefixes = {code[:2] for code in regions}
    if not {"51", "52"}.issubset(prefixes):
        raise ValueError("강원 51, 전북 52 코드를 확인하세요.")
    if prefixes & {"42", "45"}:
        raise ValueError("강원·전북의 이전 코드가 남았습니다.")

    values = []
    for code, (sido_name, sigungu_name) in sorted(regions.items()):
        values.append(
            "    ("
            + ", ".join(
                sql_string(value)
                for value in (code, sido_name, sigungu_name)
            )
            + ")"
        )

    sql = (
        "-- Source: https://www.code.go.kr/stdcode/regCodeL.do\n"
        "-- Downloaded: 2026-10-08\n"
        "-- Generated by scripts/generate_regions.py\n\n"
        "INSERT INTO regions (region_code, sido_name, sigungu_name)\n"
        "VALUES\n"
        + ",\n".join(values)
        + ";\n"
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(sql, encoding="utf-8")
    print(f"지역 {len(regions)}개 생성 완료")
    print(f"저장 위치: {OUTPUT}")


if __name__ == "__main__":
    main()
